config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/function", to: "static_pages#function"
  get "/pricing", to: "static_pages#pricing"
  get "/terms", to: "static_pages#terms"
  get "/privacy_policy", to: "static_pages#privacy_policy"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  enum status: {
    pending: 0,
    before_starting: 1,
    structure_create: 2,
    structure_collection: 3,
    writing_create: 4,
    writing_collection: 5,
    cms_create: 6,
    cms_collection: 7,
    structure_checking: 8,
    writing_checking: 9,
    cms_checking: 10,
    writer_checking: 11,
    select_keyword: 12,
    client_checking: 13,
    other_task: 14
  }

  def status_text
    I18n.t("enums.project.status.#{status}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! unless email.nil? }
  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: {with: VALID_EMAIL_REGEX}, uniqueness: {message: 'はすでに登録されています'}
  LETTER_NUMBER_MIXED = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i
  validates :password, length: { minimum: 10 }, format: { with: LETTER_NUMBER_MIXED, message: 'は半角英数字の両方を含んでください' }
  validates :password_confirmation, presence: true
  has_secure_password
  has_many :projects

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # セッションハイジャック防止のためにセッショントークンを返す
  # 記憶ダイジェストを再利用しているのは利便性のため
  def session_token
    remember_digest || remember
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    date_today
    project_table
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(project_params)
     if @project.save
      redirect_to projects_path, notice: 'プロジェクトが正常に作成されました。'
    else
      @projects = Project.all
      render :index, status: :unprocessable_entity
    end
  end

  def edit
  end

  private
    def project_params
      params.require(:project).permit(:client, :title, :status, :other_task, :task_deadline, :final_deadline, :final_deadline_not_applicable, :compensation, :url, :note)
    end

    def date_today
      # 基準日を設定（デフォルトは今月）
      @today = Date.today
      @base_date = params[:base_date].present? ? Date.parse(params[:base_date]) : @today

      # 基準月の最初と最後の日を取得
      @current_month_first_day = @base_date.beginning_of_month
      @current_month_last_day = @base_date.end_of_month
      @next_month_first_day = @current_month_first_day.next_month
      @next_month_last_day = @next_month_first_day.end_of_month

      # 日付の設定
      @wday_jan = ["日","月","火","水","木","金","土"]
      @current_month = @current_month_first_day.month
      @next_month = @next_month_first_day.month
      @current_year = @current_month_first_day.year
      @next_year = @next_month_first_day.year

      # 月の合計日数を取得
      @current_days_in_month = (@current_month_first_day..@current_month_last_day).count
      @next_days_in_month = (@next_month_first_day..@next_month_last_day).count

      # 基準月の日付を配列に格納
      @current_calendar_data = []
      (@current_month_first_day..@current_month_last_day).each do |date|
        @current_calendar_data << {
          date: date,
          year: date.year,
          month: date.month,
          day: date.day,
          wday: date.wday,
          today: date == @today
        }
      end

      # 次月の日付を配列に格納
      @next_calendar_data = []
      (@next_month_first_day..@next_month_last_day).each do |date|
        @next_calendar_data << {
          date: date,
          year: date.year,
          month: date.month,
          day: date.day,
          wday: date.wday,
          today: date == @today
        }
      end

      # 基準月から2か月分の日付を格納
      @two_months_calendar_data = @current_calendar_data + @next_calendar_data
    end

    def project_table
      
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user&& @user.authenticate(params[:session][:password])
      reset_session
      params[:session][:remember_me] == "1" ? remember(@user) : forget(@user)
      log_in @user
      redirect_to projects_path
    else
      flash.now[:danger] = "メールアドレスまたはパスワードが間違っています"
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def function
  end

  def pricing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  # 新しいユーザーを作成する（新規登録）
  def new
    @user = User.new
  end

  # ユーザーでログインする
  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      redirect_to projects_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  # ユーザー情報を編集するページを表示する
  def edit
    @user = User.find(params[:id])
  end

  # ユーザー情報を更新する
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "ユーザー情報が更新されました"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "WriterTask"
    home_title = "WriterTask - ライター案件管理ツール"
    if page_title.empty?
      home_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
    session[:session_token] = user.session_token
  end

  # 永続的セッションのためにユーザーをデータベースに記憶する
  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      user = User.find_by(id: user_id)
      if user && session[:session_token] == user.remember_digest
        @current_user = user
      end
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-container">
    <ul>
      <li><%= link_to "ヘルプ", help_path %></li>
      <li><%= link_to "利用規約", terms_path %></li>
      <li><%= link_to "プライバシーポリシー", privacy_policy_path %></li>
      <li><%= link_to "お問い合わせ", contact_path %></li>
      <li><%= link_to "運営者", about_path %></li>
    </ul>
  </div>
  <%= debug(params) if Rails.env.development? %>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="header-container">
      <div id="container logo-container">
        <% if logged_in? %>
          <h1><%= link_to image_tag("WriterTaskLogo", alt: "WriterTaskロゴ", width: 50, height: 50), projects_path %></h1>
        <% else %>
          <h1><%= link_to image_tag("WriterTaskLogo", alt: "WriterTaskロゴ", width: 50, height: 50), root_path %></h1>
        <% end %>
      </div>
      <div class="header-right-container">           
        <div class="header-icon" id="open-menu">
          <%= image_tag("menu", alt: "menu", width: 30, height: 30)  %>
        </div>
        <div class="header-sidebar">
          <div class="close-icon">           
            <div id="close-menu">
              <%= image_tag("close", alt: "menu", width: 30, height: 30) %>
            </div>
          </div>
          <div class="header-sidebar-menu">
            <ul>
              <% if logged_in? %>                    
              <li><%= link_to "ログアウト", logout_path, data: { turbo_method: :delete } %></li>
              <% else %>
              <li><%= link_to "ログイン", login_path %></li>
              <li><%= link_to "アカウント作成", signup_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="icon" href=<%= asset_path "WriterTaskLogo.png" %>>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main>
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/projects/index.html.erb
<% provide(:title, "案件管理") %>
<div class="container projects-container">
  <div class="projects-sidebar">
    <li>○○○</li>
    <li>○○○</li>
    <li>○○○</li>
  </div>
  <div id="projects-item-table-container">
    <%= %>
    <table id="projects-item-table">
      <tr>
        <th rowspan="2" class="numbers">No</th>
        <th rowspan="2" class="client">クライアント</th>
        <th rowspan="2" class="project-name">名前</th>
        <th rowspan="2" class="type">種類</th>
        <th rowspan="2" class="status">ステータス</th>
      </tr>
      <tr></tr>
      <tr>
        <td class="numbers">1</td>
        <td class="client">A社</td>
        <td class="project-name">クレジットカード おすすめ</td>
        <td class="type">構成</td>
        <td class="status">未着手</td>
      </tr>
    </table>
  </div>
  <div id="projects-date-table-container">
    <table id="projects-date-table">       
      <tr>
        <th colspan="<%= @current_days_in_month %>" class="year-month "><%= @current_year %>/<%= @current_month %></th>
        <th colspan="<%= @next_days_in_month %>" class="year-month"><%= @next_year %>/<%= @next_month %></th>
      </tr>
      <tr>
        <% @two_months_calendar_data.each do |data| %>
          <th class="calendar-day"><%= data[:month] %>/<%= data[:date].day %></th>
        <% end%>
      </tr>
    </table>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert">
      ご入力いただいたフォームには<%= @user.errors.count %>つの誤りがあります。
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "運営者") %>
<h1>運営者</h1>
<p>ライター案件管理ツールを開発・運営しているのは、フリーとして活動するWebライターの小川です。</p>
<p>ライターのブログも運営しているので、こちらもどうぞ。</p>
<a href="https://brook-writer.com/" target="_blank">Webライターの書斎</a>

app/views/static_pages/contact.html.erb
<% provide(:title, "お問い合わせ") %>
<h1>お問い合わせ</h1>
<p>ご不明点やご要望など、運営者に問い合わせたい内容がある場合、お手数ですが下記フォームまでお願いします。</p>
<div>
  <label for="name">お名前</label>
  <input type="text" id="name">
</div>
<div>
  <label for="mail">メールアドレス</label>
  <input type="text" id="mail">
</div>
<div>
  <label for="content">お問い合わせ内容</label>
  <textarea id="content"></textarea>
</div>
<div>
  <button>送信</button>
</div>

app/views/static_pages/function.html.erb
<% provide(:title, "機能") %>
<h1>機能</h1>
<p>WriterTaskの機能は、次の通りです。</p>
<ul>
<li>案件管理（納期や進捗状況など）</li>
<li>月間報酬管理（毎月の報酬確認や目標報酬の達成度など）</li>
</ul>

app/views/static_pages/help.html.erb
<% provide(:title, "ヘルプ") %>
<h1>ヘルプ</h1>
<p>ライター案件管理ツールのヘルプです</p>
<h2>ヘルプ①</h2>
<p>ヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプ</p>
<h2>ヘルプ②</h2>
<p>ヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプ</p>
<h2>ヘルプ③</h2>
<p>ヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプヘルプ</p>

app/views/static_pages/home.html.erb
<h1>ライター案件管理ツール</h1>
<p>ライターが案件を管理できるツールです。</p>

app/views/static_pages/pricing.html.erb
<% provide(:title, "料金") %>
<h1>料金</h1>
<p>WriterTaskは無料で利用できます。</p>

app/views/static_pages/privacy_policy.html.erb
<% provide(:title, "プライバシーポリシー") %>

<div class="terms-policy-container">
  <div class="terms-policy-date">
    <p>プライバシーポリシー作成日：2024年8月3日</p>
    <p>プライバシーポリシーの最終更新日：2024年8月3日</p>
  </div>

  <div class="container terms-policy">
    <h1>プライバシーポリシー</h1>
    <p>運営者は、本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における、ユーザーの個人情報の取扱いについて、以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます。）を定めます。</p>

    <h2>第1条（個人情報）</h2>
    <p>「個人情報」とは、個人情報保護法にいう「個人情報」を指すものとし、生存する個人に関する情報であって、当該情報に含まれる氏名、生年月日、住所、電話番号、連絡先その他の記述等により特定の個人を識別できる情報及び容貌、指紋、声紋にかかるデータ、及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>

    <h2>第2条（個人情報の収集方法）</h2>
    <p>運営者は、ユーザーが利用登録をする際に氏名、生年月日、住所、電話番号、メールアドレス、銀行口座番号、クレジットカード番号、運転免許証番号などの個人情報をお尋ねすることがあります。また、ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,運営者の提携先（情報提供元、広告主、広告配信先などを含みます。以下、｢提携先｣といいます。）などから収集することがあります。</p>

    <h2>第3条（個人情報を収集・利用する目的）</h2>
    <p>運営者が個人情報を収集・利用する目的は、以下のとおりです。</p>
    <ul>
      <li>運営者サービスの提供・運営のため</li>
      <li>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
      <li>ユーザーが利用中のサービスの新機能、更新情報、キャンペーン等及び運営者が提供する他のサービスの案内のメールを送付するため</li>
      <li>メンテナンス、重要なお知らせなど必要に応じたご連絡のため</li>
      <li>利用規約に違反したユーザーや、不正・不当な目的でサービスを利用しようとするユーザーの特定をし、ご利用をお断りするため</li>
      <li>ユーザーにご自身の登録情報の閲覧や変更、削除、ご利用状況の閲覧を行っていただくため</li>
      <li>有料サービスにおいて、ユーザーに利用料金を請求するため</li>
      <li>上記の利用目的に付随する目的</li>
    </ul>

    <h2>第4条（利用目的の変更）</h2>
    <p>運営者は、利用目的が変更前と関連性を有すると合理的に認められる場合に限り、個人情報の利用目的を変更するものとします。</p>
    <p>利用目的の変更を行った場合には、変更後の目的について、運営者所定の方法により、ユーザーに通知し、または本ウェブサイト上に公表するものとします。</p>

    <h2>第5条（個人情報の第三者提供）</h2>
    <p>運営者は、次に掲げる場合を除いて、あらかじめユーザーの同意を得ることなく、第三者に個人情報を提供することはありません。ただし、個人情報保護法その他の法令で認められる場合を除きます。</p>
    <p>人の生命、身体または財産の保護のために必要がある場合であって、本人の同意を得ることが困難であるとき</p>
    <p>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって、本人の同意を得ることが困難であるとき</p>
    <p>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</p>
    <p>予め次の事項を告知あるいは公表し、かつ運営者が個人情報保護委員会に届出をしたとき</p>
    <ul>
      <li>利用目的に第三者への提供を含むこと</li>
      <li>第三者に提供されるデータの項目</li>
      <li>第三者への提供の手段または方法</li>
      <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
      <li>本人の求めを受け付ける方法</li>
    </ul>
    <p>前項の定めにかかわらず、次に掲げる場合には、当該情報の提供先は第三者に該当しないものとします。</p>
    <ul>
      <li>運営者が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
      <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
      <li>個人情報を特定の者との間で共同して利用する場合であって、その旨並びに共同して利用される個人情報の項目、共同して利用する者の範囲、利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について、あらかじめ本人に通知し、または本人が容易に知り得る状態に置いた場合</li>
    </ul>

    <h2>第6条（個人情報の開示）</h2>
    <p>運営者は、本人から個人情報の開示を求められたときは、本人に対し、遅滞なくこれを開示します。ただし、開示することにより次のいずれかに該当する場合は、その全部または一部を開示しないこともあり、開示しない決定をした場合には、その旨を遅滞なく通知します。なお、個人情報の開示に際しては、1件あたり1,000円の手数料を申し受けます。</p>
    <ul>
      <li>本人または第三者の生命、身体、財産その他の権利利益を害するおそれがある場合</li>
      <li>運営者の業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
      <li>その他法令に違反することとなる場合</li>
    </ul>
    <p>前項の定めにかかわらず、履歴情報および特性情報などの個人情報以外の情報については、原則として開示いたしません。</p>

    <h2>第7条（個人情報の訂正および削除）</h2>
    <p>ユーザーは、運営者の保有する自己の個人情報が誤った情報である場合には、運営者が定める手続きにより、運営者に対して個人情報の訂正、追加または削除（以下、「訂正等」といいます。）を請求することができます。</p>
    <p>運営者は、ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の訂正等を行うものとします。</p>
    <p>運営者は、前項の規定に基づき訂正等を行った場合、または訂正等を行わない旨の決定をしたときは遅滞なく、これをユーザーに通知します。</p>

    <h2>第8条（個人情報の利用停止等）</h2>
    <p>運営者は、本人から、個人情報が、利用目的の範囲を超えて取り扱われているという理由、または不正の手段により取得されたものであるという理由により、その利用の停止または消去（以下、「利用停止等」といいます。）を求められた場合には、遅滞なく必要な調査を行います。</p>
    <p>前項の調査結果に基づき、その請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の利用停止等を行います。</p>
    <p>運営者は、前項の規定に基づき利用停止等を行った場合、または利用停止等を行わない旨の決定をしたときは、遅滞なく、これをユーザーに通知します。</p>
    <p>前2項にかかわらず、利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって、ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は、この代替策を講じるものとします。</p>

    <h2>第9条（プライバシーポリシーの変更）</h2>
    <p>本ポリシーの内容は、法令その他本ポリシーに別段の定めのある事項を除いて、ユーザーに通知することなく、変更することができるものとします。</p>
    <p>運営者が別途定める場合を除いて、変更後のプライバシーポリシーは、本ウェブサイトに掲載したときから効力を生じるものとします。</p>
    <h2>第10条（お問い合わせ窓口）</h2>
    <p>本ポリシーに関するお問い合わせは、下記の窓口までお願いいたします。</p>
    <br>
    <p>住所：北海道札幌市中央区南5条西15丁目2-3　リズム医大前503号室 </p>
    <p>担当者：小川 遼</p>
    <p>Eメールアドレス：info@brook-writer.com</p>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "新規登録") %>
<div class="container form-container">
  <h1>新規アカウント作成</h1>
  <%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="form-group">
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control', required: true %>
      <small class="form-text">※10文字以上、半角英数字の両方を含んでください</small>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
    </div>
    <div class="form-group">
      <small>WriterTaskへのアカウント登録で<%= link_to "利用規約", terms_path %>および<%= link_to "プライバシーポリシー", privacy_policy_path %>に同意したものとみなします。</small>
    </div>
    <div class="form-group">
      <%= f.submit "アカウント作成", class: 'btn btn-fill btn-submit' %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>